apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.4.1
        args:
          - '-storage.local.retention=48h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-storage.local.path=/prometheus'
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 500m
            memory: 4Gi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: prometheus-core
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: prometheus-storage
        {{- else }}
        emptyDir: {}
        {{- end }}